# Generated by Django 5.0.4 on 2024-04-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.iconsdb.com%2Fgray-icons%2Fx-mark-icon.html&psig=AOvVaw1qpsFJlSppSEpi6xL18APi&ust=1714515918349000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMCc0dO76IUDFQAAAAAdAAAAABAE'),
        ),
    ]
