# Generated by Django 5.0.4 on 2024-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL5UMX3Vv8t5CzcGOIhMClknq7AOSttL7yj4RAkYCSAg&s'),
        ),
    ]
